In [36]:
import pyvista as pv
import numpy as np

In [37]:

contactpoints = np.array([[0.5,0,0],[0,0.5,0]])
contactnormals = np.array([[1,0,0],[0,1,0]])
contactpoints[0].shape

(3,)

In [38]:
center = [4,4,1]
#sphere = pv.ParametricEllipsoid(1,1,1)
sphere = pv.Sphere(1,center,theta_resolution=100,phi_resolution=100)
print(sphere.points)

contactpoints = np.array([[0.9,0,0],[0,0.9,0]])
contactnormals = np.array([[1,0,0],[0,1,0]])

for contactpoint,contactnormal in zip(contactpoints,contactnormals):
    contactpoint=np.expand_dims(contactpoint,0)
    contactnormal=np.expand_dims(contactnormal,0)
    projection = np.inner(np.array(sphere.points-center)-contactpoint,contactnormal)
    transformedpoints = np.where(projection>0,sphere.points-projection*contactnormal,sphere.points)
    sphere.points = transformedpoints


[[4.0000000e+00 4.0000000e+00 2.0000000e+00]
 [4.0000000e+00 4.0000000e+00 0.0000000e+00]
 [4.0317278e+00 4.0000000e+00 1.9994965e+00]
 ...
 [4.0948687e+00 3.9940314e+00 4.5281053e-03]
 [4.0632987e+00 3.9960177e+00 2.0133257e-03]
 [4.0316653e+00 3.9980078e+00 5.0348043e-04]]


In [39]:
p = pv.Plotter()
p.add_mesh(sphere, color='lightblue', show_edges=False)
p.show()

Widget(value='<iframe src="http://localhost:57114/index.html?ui=P_0x146c3044080_14&reconnect=auto" class="pyvi…