In [1]:
import scipy.io
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
import os
from tqdm import tqdm

In [2]:
from Encoding import load
dataset_name = "2Sphere"
par_data, bc = load(dataset_name,data_type="par_data"), load(dataset_name,data_type="bc")

In [3]:
from Encoding import ProjectPointsToCylinder, ProjectPointsToHyperplane, ConstructTopology
par = par_data[0][0]
bc_t = bc[0]
super_topology = ConstructTopology(par,bc_t,4)

In [4]:
from Encoding import TopologySlice, CheckForWallContact
from Evaluation import NumpyGroupby


from Encoding import TopologyFromPlausibleTopology
print(bc_t.shape)
topology = TopologyFromPlausibleTopology(super_topology,par,bc_t)

(2, 6, 9)


In [5]:
topology.shape, super_topology.shape

((5, 2), (13, 2))

In [ ]:

from Encoding import GetVirtualParticlesCoords
P_wall, normal_vectors = GetVirtualParticlesCoords(par,topology,bc_t)

P_virtual = np.concatenate((P_wall,
                            np.zeros((P_wall.shape[0],3)),                      
                            normal_vectors,
                            np.zeros((P_wall.shape[0],1))),                      
                            axis=1)
print(P_wall)
top_new = topology.copy()
n_new = P_virtual.shape[0]
n_par = par.shape[0]
top_new[-n_new:,1] = np.arange(n_par,n_new+n_par,1)
print(top_new)
    

[[ 3.2771032e-01  7.0110654e-08  3.2672719e-01]
 [-1.1330610e-07  3.2771032e-01 -3.2672719e-01]
 [ 1.3670361e-07  3.2771032e-01  3.2672719e-01]
 [-3.2771032e-01  3.0674740e-08 -3.2672719e-01]]
[[ 0  1]
 [ 1 -4]
 [ 1 -2]
 [ 0 -2]
 [ 0 -1]] 4 2
[[0 1]
 [1 2]
 [1 3]
 [0 4]
 [0 5]]


In [17]:
np.arange(n_new,n_new+n_par,1)

array([4, 5, 6, 7])

In [ ]:
bc.shape

In [ ]:
from Encoding import BCEncoding

P_virtual, top_new = BCEncoding(par_data[0][0],top,bc_t)
P_virtual, top_new

In [ ]:
point_on_wall = ProjectPointsToCylinder(particles,cyl)
#point_on_wall = ProjectPointsToHyperplane(particles,wall)


In [ ]:
from Plotting import Plot3DVectors
#fig = plt.figure()
#ax = fig.add_subplot(projection='3d')
#Plot3DVectors(ax,axis_projection,s)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
vector = P_virtual[:,:3]
x = vector[:,0]
y = vector[:,1]
z = vector[:,2]
ax.scatter(x,y,z)

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
vector = point_on_wall
x = vector[:,0]
y = vector[:,1]
z = vector[:,2]
ax.scatter(x,y,z)
vector = particles
x = vector[:,0]
y = vector[:,1]
z = vector[:,2]
ax.scatter(x,y,z)

In [ ]:
vector = point_on_wall
x = vector[:,0]
y = vector[:,1]
z = vector[:,2]
plt.plot(y,z,'o',color='b')
vector = particles
x = vector[:,0]
y = vector[:,1]
z = vector[:,2]
plt.plot(y,z,'o',color='r')